version: "2"

#
# ---Choose Your Languages---
# To disable analysis for a certain language, set the language to `false`.
# For help setting your languages:
# http://docs.codeclimate.com/article/169-configuring-analysis-languages
#
languages:
  Ruby: false
  Javascript: false
  PHP: false
  Python: true


#
# ---Set Your Quality Metrics---
# To disable analysis for a certain metrics, set the metric to `false`.
# For help setting your quality metrics:
# https://docs.codeclimate.com/docs/advanced-configuration
#
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: true
  method-lines:
    enabled: true
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: true
  identical-code:
    enabled: true


#
# ---Configuring Plugins---
# To disable analysis for a certain plugins, set to `false`.
# For help setting your plugins:
# https://docs.codeclimate.com/docs/advanced-configuration
# For list of these plugins:
# https://docs.codeclimate.com/docs/list-of-engines
#

plugins:
  pep8:
    enabled: true  



#
# ---Exclude Files or Directories---
# List the files or directories you would like excluded from analysis.
# For help setting your exclude paths:
# https://docs.codeclimate.com/docs/advanced-configuration#section-exclude-patterns
#
exclude_paths:
 - "docs/"
 - "docker/"
 - "notebooks/"
 - "config/"
 - "db/"
 - "dist/"
 - "features/"
 - "**/node_modules/"
 - "**/spec/"
 - "**/test/"
 - "**/tests/"
 - "Tests/"
 - "**/vendor/"
 - "**/*_test.go"
 - "**/*.d.ts"
 - "**/__pycache__"
 - "**.js"
